name: Q1 Docker Build

on:
  push:
    branches: [ "q1" ]
  pull_request:
    branches: [ "main" ]

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: docker build -t q1-app .

      # Optional: run the container (recommended for your assignment)
      - name: Run container
        run: docker run --rm q1-app