name: Q1 Docker Build

on:
  push:
    branches: [ "question1" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: :contentReference[oaicite:0]{index=0}@v4

    - name: Set up Docker
      uses: :contentReference[oaicite:1]{index=1}@v3

    - name: Build Docker image
      run: docker build -t q1-app .

    - name: Run container
      run: docker run --rm q1-app